[問題](../README.md)

***
# 039：解答例
finally 節の処理が try の例外処理より優先されるため、finally 節の throw が catch され、 2nd が出力されて終了する。

[ソースコード(Knock039.java)](src/Knock039.java)
